### Criar Desafio Premium com Imagem de Capa Real
POST https://rumo-ao-shape-api.onrender.com/challenges
Content-Type: multipart/form-data; boundary=boundary-monstro

--boundary-monstro
Content-Disposition: form-data; name="title"

Desafio Projeto Verão 2026
--boundary-monstro
Content-Disposition: form-data; name="description"

Foco total, 5 treinos por semana ou perde o Pix!
--boundary-monstro
Content-Disposition: form-data; name="creatorId"
Content-Type: text/plain

7d2698ef-a55a-479f-867f-7d2de1e79d17
--boundary-monstro
Content-Disposition: form-data; name="metaSemanal"

5
--boundary-monstro
Content-Disposition: form-data; name="taxaInscricao"

0
--boundary-monstro
Content-Disposition: form-data; name="valorCaucao"

50.00
--boundary-monstro
Content-Disposition: form-data; name="startDate"

2026-06-01T00:00:00.000Z
--boundary-monstro
Content-Disposition: form-data; name="endDate"

2026-06-30T23:59:59.000Z
--boundary-monstro
Content-Disposition: form-data; name="image"; filename="capa.jpg"
Content-Type: image/jpeg

< ./capa.jpg
--boundary-monstro--

### ENtrar no desafio criado
POST https://rumo-ao-shape-api.onrender.com/challenges/8b56f53e-709a-4861-be6d-7b51f985bad9/join
Content-Type: application/json

{
  "userId": "7d2698ef-a55a-479f-867f-7d2de1e79d17"
}

#### Listar Desafios (Ver se o que criamos aparece)
GET https://rumo-ao-shape-api.onrender.com/challenges
Content-Type: application/json

### Usuário desiste e sai do desafio (Perde a caução)
POST https://rumo-ao-shape-api.onrender.com/challenges/8b56f53e-709a-4861-be6d-7b51f985bad9/leave
Content-Type: application/json

{
  "userId": "7d2698ef-a55a-479f-867f-7d2de1e79d17"
}

### Usuário solicita entrada no desafio (Gera Pix Real no Asaas Sandbox)
POST https://rumo-ao-shape-api.onrender.com/challenges/8b56f53e-709a-4861-be6d-7b51f985bad9/join
Content-Type: application/json

{
  "userId": "7d2698ef-a55a-479f-867f-7d2de1e79d17"
}