@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZTQ5MGMyMC04Mzc2LTQ5NDYtOWE1NS03OTU5OGM1Njg0NjEiLCJlbWFpbCI6Im1vbnN0cm9Ac2hhcGUuY29tIiwicGxhbiI6IkZSRUUiLCJpYXQiOjE3ODA5Mzc0NzEsImV4cCI6MTc4MTU0MjI3MX0.GmF0yGsVabvVFNWHgHXh6CABlAoOpG1QEuc54g1R09c
@challengeId = a9f4b10e-4657-4c91-a88a-13193b76d746
@targetUserId = 7d2698ef-a55a-479f-867f-7d2de1e79d17

### 1. Criar Desafio Premium com Imagem de Capa Real (Inscrição Automática do Criador)
POST http://localhost:3000/challenges
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary-monstro

--boundary-monstro
Content-Disposition: form-data; name="title"

Desafio Projeto Verão 2026
--boundary-monstro
Content-Disposition: form-data; name="description"

Foco total, 5 treinos por semana ou perde o Pix!
--boundary-monstro
Content-Disposition: form-data; name="creatorId"

{{targetUserId}}
--boundary-monstro
Content-Disposition: form-data; name="metaSemanal"

5
--boundary-monstro
Content-Disposition: form-data; name="taxaInscricao"

0
--boundary-monstro
Content-Disposition: form-data; name="valorCaucao"

50.00
--boundary-monstro
Content-Disposition: form-data; name="startDate"

2026-06-01T00:00:00.000Z
--boundary-monstro
Content-Disposition: form-data; name="endDate"

2026-06-30T23:59:59.000Z
--boundary-monstro
Content-Disposition: form-data; name="isFree"

false
--boundary-monstro
Content-Disposition: form-data; name="image"; filename="capa.jpg"
Content-Type: image/jpeg

< ./capa.jpg
--boundary-monstro--


### 2. Listar Todos os Desafios Globais (Aba Explorar)
GET http://localhost:3000/challenges
Authorization: Bearer {{token}}
Content-Type: application/json


### 3. Entrar em um Desafio (Gera Pix no Asaas Sandbox ou Ativa Direto se Gratuito)
# O ID do usuário logado é extraído pelo @CurrentUser() direto do Bearer Token
POST http://localhost:3000/challenges/{{challengeId}}/join
Authorization: Bearer {{token}}
Content-Type: application/json

{}


### 4. Sair/Abandonar um Desafio Ativo (Aplica retenção da Caução)
# O ID do usuário logado é extraído pelo @CurrentUser() direto do Bearer Token
POST http://localhost:3000/challenges/{{challengeId}}/leave
Authorization: Bearer {{token}}
Content-Type: application/json

{}


### 5. Buscar Desafios Criados e Gerenciados por um Usuário (Painel do Administrador)
GET http://localhost:3000/challenges/creator/{{targetUserId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### 6. Buscar Participações Ativas do Usuário (Cards da Home do Flutter)
GET http://localhost:3000/challenges/active-participations/{{targetUserId}}
Authorization: Bearer {{token}}
Content-Type: application/json


### 7. Buscar Histórico Completo de Inscrições do Usuário (Aba Desafios Passados / Perfil)
GET http://localhost:3000/challenges/history/{{targetUserId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### 8. Editar Desafio Pendente (Permite alterar tudo)
PATCH http://localhost:3000/challenges/{{challengeId}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary-monstro

--boundary-monstro
Content-Disposition: form-data; name="title"

Desafio Projeto Verão Atualizado 2027
--boundary-monstro
Content-Disposition: form-data; name="description"

Nova descrição alterada localmente com sucesso!
--boundary-monstro
Content-Disposition: form-data; name="startDate"

2026-06-10T00:00:00.000Z
--boundary-monstro
Content-Disposition: form-data; name="image"; filename="nova-capa.jpg"
Content-Type: image/jpeg

< ./capa.jpg
--boundary-monstro--


### 9. Forçar Erro ao tentar mudar textos de Desafio Ativo (Mude o ID para um desafio ACTIVE)
PATCH http://localhost:3000/challenges/{{challengeId}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary-monstro

--boundary-monstro
Content-Disposition: form-data; name="title"

Tentativa de burlar nome de sala ativa
--boundary-monstro--


### 10. Deletar um Desafio Permanentemente
DELETE http://localhost:3000/challenges/{{challengeId}}
Authorization: Bearer {{token}}
Content-Type: application/json

### 11. Entrar em um Desafio por Código de Convite (Fácil e Rápido)
POST http://localhost:3000/challenges/join-by-code
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "inviteCode": "6790E518"
}

### 12. Buscar Detalhes Completos de um Desafio por UUID (Timeline + Check-ins)
GET http://localhost:3000/challenges/{{challengeId}}
Authorization: Bearer {{token}}
Content-Type: application/json