### Variáveis locais
@baseUrl = http://localhost:3000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZDI2OThlZi1hNTVhLTQ3OWYtODY3Zi03ZDJkZTFlNzlkMTciLCJlbWFpbCI6InBhbmd6aW5uMkBnbWFpbC5jb20iLCJwbGFuIjoiUFJFTUlVTSIsImlhdCI6MTc4MDY2NTYwOCwiZXhwIjoxNzgxMjcwNDA4fQ.9voHx2bZAKsaA1qTUbGSWKyMmZvrYVWVw0ZaKtaC-ko

@userId = 7d2698ef-a55a-479f-867f-7d2de1e79d17
@challengeId = aa4fdb6d-3d9c-4a4a-b365-9c10a9a4aaee

### Enviar um treino válido anexando a foto do shape
POST {{baseUrl}}/checkins
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary_do_monstro

--boundary_do_monstro
Content-Disposition: form-data; name="userId"

{{userId}}
--boundary_do_monstro
Content-Disposition: form-data; name="challengeId"

{{challengeId}}
--boundary_do_monstro
Content-Disposition: form-data; name="latitude"

-23.550520
--boundary_do_monstro
Content-Disposition: form-data; name="longitude"

-46.633308
--boundary_do_monstro
Content-Disposition: form-data; name="deviceUuid"

iphone_15_pro_max_hardware_id
--boundary_do_monstro
Content-Disposition: form-data; name="image"; filename="teste_shape.jpg"
Content-Type: image/jpeg

< ./capa.jpg
--boundary_do_monstro--