### Variáveis Locais de Ambiente
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZTQ5MGMyMC04Mzc2LTQ5NDYtOWE1NS03OTU5OGM1Njg0NjEiLCJlbWFpbCI6Im1vbnN0cm9Ac2hhcGUuY29tIiwicGxhbiI6IkZSRUUiLCJpYXQiOjE3ODI1MDExMjIsImV4cCI6MTc4MzEwNTkyMn0.eHaB96teyzXU8k0l-9WFZ5fqziJS-YPU95KZOT8lZ44
@challengeId = a9f4b10e-4657-4c91-a88a-13193b76d746


### 🚀 1. Solicitar Entrada em Desafio (Gera PIX de Inscrição)
POST {{baseUrl}}/challenges/{{challengeId}}/join
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "paymentType": "PIX"
}


### 🚀 2. Pagar Multa por quebra de meta Semanal
POST {{baseUrl}}/payments/fine
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "challengeId": "{{challengeId}}",
  "value": 20.00,
  "description": "Multa por furação de meta na semana 2 - Rumo Ao Shape"
}