### Simular o Disparo de Confirmação de Pagamento do Webhook do Asaas
POST https://87ec-179-97-23-12.ngrok-free.app/webhooks/asaas
Content-Type: application/json
asaas-access-token: whsec_6XdTJIQNxnufj1A1yN9FHmzbyiVgu78ItonnDv7jfqc

{
    "id": "evt_simulado_local_9999",
    "event": "PAYMENT_CONFIRMED",
    "dateCreated": "2026-05-28 22:00:00",
    "payment": {
        "id": "pay_j042bx2ylkv9p61h",
        "object": "payment",
        "value": 65.00,
        "status": "CONFIRMED",
        "externalReference": "93906334-892b-442c-a7ae-b315633286f6"
    }
}