### Simular o Disparo de Confirmação de Pagamento do Webhook do Asaas
POST https://rumo-ao-shape-api.onrender.com/webhooks/asaas
Content-Type: application/json
asaas-access-token: whsec_6XdTJIQNxnufj1A1yN9FHmzbyiVgu78ItonnDv7jfqc

{
    "id": "evt_simulado_local_9999",
    "event": "PAYMENT_CONFIRMED",
    "dateCreated": "2026-05-28 22:00:00",
    "payment": {
        "id": "pay_00qdw9omgprzmmkf",
        "object": "payment",
        "value": 65.00,
        "status": "CONFIRMED",
        "externalReference": "cde9a4f1-487d-43b9-bdf7-58a948787169"
    }
}